spring.application.name=medisphere-backend

server.port=8080

spring.data.mongodb.uri=mongodb://localhost:27017/medisphere

# Kafka (optional)
#spring.kafka.bootstrap-servers=localhost:9092
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer